PC_MODE = False

SENSOR_CONFIGURED = "LIGHT"  # "LIGHT"
ACTUATOR_CONFIGURED = "BUZZER"  # "BUZZER"

# URL_POST_ACTUATION_EDGE = "http://127.0.0.1:8001"
URL_POST_ACTUATION_EDGE = "http://192.168.1.101:8001"
URL_POST_ACTUATION_CLOUD = ""

IOTMA_SENSOR_NAME = "RainSensor"
